# Streamlit Cloud Secrets Configuration
# This file should be uploaded to your Streamlit Cloud app settings
# DO NOT commit this file to your repository with real passwords

# Dashboard password - change this to your desired password
STREAMLIT_PASSWORD = "Yonathan_Shiri_2025"

# Optional: Add other configuration
[general]
app_name = "STT Enhancement Evaluation Dashboard"
environment = "production"

# Instructions for deployment:
# 1. Go to your Streamlit Cloud app settings
# 2. Navigate to the "Secrets" section
# 3. Copy the contents of this file (with your real password)
# 4. Paste it in the secrets text area
# 5. Save the configuration 